name: Docker Build

on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-demo-image:latest .

      - name: Verify Docker image
        run: docker images my-demo-image:latest
