name: Docker Build and Test

on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-demo-image:latest .

      - name: Run container
        run: docker run -d -p 8080:80 --name my-demo-container my-demo-image:latest

      - name: Test container
        run: curl --fail http://localhost:8080

      - name: Stop container
        run: docker stop my-demo-container
